# Generated by Django 2.0.2 on 2018-03-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Dropped'), ('P', 'Passed course'), ('F', 'Failed course')], default='A', max_length=1),
        ),
    ]
