# Generated by Django 2.0.2 on 2018-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='progress_status',
            field=models.CharField(choices=[('B', 'Behind schedule'), ('O', 'On pace'), ('A', 'Ahead of schedule'), ('N', 'No progress')], default='N', max_length=1),
        ),
    ]
