# Generated by Django 2.0.2 on 2018-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20180317_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='progress_status',
            field=models.CharField(choices=[('B', 'Behind schedule'), ('O', 'On pace'), ('A', 'Ahead of schedule'), ('N', 'No progress'), ('NC', 'No completed assignments')], default='N', max_length=2),
        ),
    ]
