# Generated by Django 2.0.2 on 2018-06-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20180318_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Dropped'), ('P', 'Passed course'), ('F', 'Failed course'), ('I', 'Incomplete')], default='A', max_length=1),
        ),
    ]
