from django import forms

from .models import StudentTracker


class StudentTrackerForm(forms.ModelForm):
    class Meta:
        model = StudentTracker
        fields = [
            'student_tracking_csv',
            'grade_report_csv',
        ]
        help_texts = {
            'student_tracking_csv': 'Upload a CSV version of the Python 210 SP Student Tracking file from the course'
                                    'OneDrive account.',
            'grade_report_csv': 'Upload a CSV of the student grade report generated by the EdX learning platform.'
        }
