# Generated by Django 2.0.2 on 2018-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_tracking_csv', models.FileField(upload_to='tracking_files/')),
                ('grade_report_csv', models.FileField(upload_to='tracking_files/')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
